# Aula 02 - Python 

## Dados numéricos


In [14]:
# Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [15]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [16]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [18]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [22]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


## Dados de texto

In [26]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


## Dados tipo bool - lógica

In [27]:
a == 1

True

In [30]:
h = (a==1)
print(h)
type(h)

True


bool

In [31]:
h = (a==2)
print(h)
type(h)

False


bool

In [34]:
i = True
type(i)

bool

In [35]:
ii = 'True'
type(ii)

str


#### Operação de comparação 

In [37]:
# Operação ==
a==b

True

In [38]:
# Operação ><
a>b

False

In [39]:
# Operação !=
a!=b

False

In [40]:
# Operação >= ou <=
a>=b

True

## Operações matemáticas

In [42]:
# Soma 
a+b

2.0

In [43]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [46]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [47]:
# Divisão
a/b

1.0

In [49]:
# Potencia
5**2

25

In [51]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)

22026.465794806718

In [55]:
math.exp(0)

1.0

In [56]:
math.exp(a)

2.718281828459045

In [58]:
math.exp(-10)

4.5399929762484854e-05

In [60]:
import math as mt
mt.log(c)

0.0

In [61]:
mt.log10(100)

2.0

## Listas

In [64]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [66]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [67]:
myFirstList==a

False

In [68]:
myFirstList[0]==a

True

In [77]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [70]:
type(mySecList)

list

In [74]:
type(mySecList[2])

str

In [78]:
type(mySecList[1])

int

## Caminhos = path

In [83]:
path = r"C:\Users\Leonardo.Hoinaski\Documents\ENS410064_1"
print(path)

C:\Users\Leonardo.Hoinaski\Documents\ENS410064_1


In [84]:
path = "C:/Users/Leonardo.Hoinaski/Documents/ENS410064_1"
print(path)

C:/Users/Leonardo.Hoinaski/Documents/ENS410064_1


In [88]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git', '.gitignore', 'dados', 'Doc1.docx', 'pyenv', 'README.md', 'scripts']

In [87]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [91]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/Leonardo.Hoinaski/Documents/ENS410064_1/.git'

In [92]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [99]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\Leonardo.Hoinaski\\Documents\\ENS410064_1\\.git'

In [100]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\Leonardo.Hoinaski\\Documents\\')

In [101]:
os.getcwd()

'C:\\Users\\Leonardo.Hoinaski\\Documents'

In [104]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

diretório já existe


In [111]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\Leonardo.Hoinaski\Documents/test2


## Numpy arrays e Pandas DataFrames

In [114]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [115]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [121]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.05078452 0.97829287 0.13950372 0.39188034 0.61730865 0.03872888
  0.57060336 0.2569905  0.51036029 0.15369759]
 [0.75772955 0.24637205 0.81203505 0.88490541 0.85044071 0.16307961
  0.46899566 0.53743524 0.40270142 0.07686154]
 [0.75614316 0.45685273 0.64750815 0.38852784 0.53084051 0.14052056
  0.642895   0.518659   0.93008863 0.34380361]
 [0.89161684 0.13049676 0.98895012 0.53191236 0.08039974 0.90916989
  0.26362699 0.70746546 0.33198333 0.56351129]
 [0.95088524 0.67709542 0.3752876  0.50219071 0.62705672 0.07321533
  0.7249236  0.38207932 0.02995971 0.92298874]
 [0.05486369 0.03368911 0.95664639 0.66888773 0.58755266 0.7628229
  0.74743534 0.09955247 0.86659315 0.51215945]
 [0.68893777 0.02981072 0.39723447 0.66158982 0.51280011 0.15481711
  0.37101771 0.04600595 0.58988553 0.75283786]
 [0.21478731 0.07847559 0.39330378 0.40993826 0.82473682 0.33431628
  0.60708222 0.02240243 0.1731405  0.86261488]
 [0.50162579 0.52478135 0.36963115 0.38144351 0.58976797 0.73917079
  0.71713707 

In [126]:
# Acessando valores da matriz
n[0,:]

array([0.05078452, 0.97829287, 0.13950372, 0.39188034, 0.61730865,
       0.03872888, 0.57060336, 0.2569905 , 0.51036029, 0.15369759])

In [128]:
n[:,0]

array([0.05078452, 0.75772955, 0.75614316, 0.89161684, 0.95088524,
       0.05486369, 0.68893777, 0.21478731, 0.50162579, 0.55540415])

In [129]:
n[:,1:5]

array([[0.97829287, 0.13950372, 0.39188034, 0.61730865],
       [0.24637205, 0.81203505, 0.88490541, 0.85044071],
       [0.45685273, 0.64750815, 0.38852784, 0.53084051],
       [0.13049676, 0.98895012, 0.53191236, 0.08039974],
       [0.67709542, 0.3752876 , 0.50219071, 0.62705672],
       [0.03368911, 0.95664639, 0.66888773, 0.58755266],
       [0.02981072, 0.39723447, 0.66158982, 0.51280011],
       [0.07847559, 0.39330378, 0.40993826, 0.82473682],
       [0.52478135, 0.36963115, 0.38144351, 0.58976797],
       [0.2486218 , 0.24131725, 0.32076594, 0.06129268]])

In [130]:
n[0,1:5]

array([0.97829287, 0.13950372, 0.39188034, 0.61730865])

In [131]:
n[0,-1]

0.15369758847080583

In [132]:
n[0,4:-1]

array([0.61730865, 0.03872888, 0.57060336, 0.2569905 , 0.51036029])

In [133]:
n[0,4:]

array([0.61730865, 0.03872888, 0.57060336, 0.2569905 , 0.51036029,
       0.15369759])

In [135]:
an = np.log(n*5)
print(an)

[[-1.37072576  1.58749172 -0.36022609  0.67263917  1.12705177 -1.6417318
   1.04837697  0.25072175  0.93679956 -0.26333041]
 [ 1.33200916  0.20852542  1.40122614  1.48716339  1.44743733 -0.20407888
   0.85227614  0.9884909   0.69987804 -0.95631171]
 [ 1.32991336  0.82604371  1.17481402  0.66404746  0.97614425 -0.35296357
   1.16766405  0.95292926  1.53696252  0.54175322]
 [ 1.49471912 -0.42696897  1.59832653  0.97816137 -0.91130637  1.5142146
   0.27621781  1.26337144  0.5067674   1.03586999]
 [ 1.55907602  1.21949485  0.62937529  0.92066259  1.14271964 -1.00491258
   1.28774891  0.64731088 -1.89846381  1.52929967]
 [-1.29346568 -1.78114287  1.56511645  1.20729887  1.0776485   1.33870853
   1.31833043 -0.69763256  1.46625224  0.94031864]
 [ 1.23683358 -1.90344929  0.68620933  1.19632839  0.94156876 -0.25607287
   0.61793244 -1.46954671  1.08161114  1.32553251]
 [ 0.07133093 -0.93552972  0.67626492  0.7176892   1.41674696  0.51377013
   1.11034686 -2.18914778 -0.14421397  1.46165097]
 [